### ISSUE TITLE
Re on the 1000+ votes bug

### ISSUE THREAD

**Issue by rebelbigfeet** [duncanlang/Letterboxd-Extras#1]
Hi, I'm the user from Firefox reviews, didn't know where else to contact you.
Thanks for fixing the issue so quickly! Now the graph looks normal even when there's a thousand+ votes.

But there's still a display bug where instead of showing for example "**80 376** 10/10 ratings (16%)" it says "**80** 10/10 ratings (16%)". See example below with "Children of Men" on Letterboxd.

<img width="253" alt="Capture d’écran 2021-09-18 à 21 51 05" src="https://user-images.githubusercontent.com/49950822/133907015-57a41d86-cc59-4c5b-b3eb-51f2494a4e45.png">
<img width="253" alt="Capture d’écran 2021-09-18 à 21 51 24" src="https://user-images.githubusercontent.com/49950822/133907023-c6cc386b-9aec-48d1-8cfc-6d6ffcc5432c.png">

**Comment by duncanlang** [comment]
I forgot about different languages using different thousand separators, so I had only accounted for commas.
It's fixed now, so just update the add-on and you'll see the correct number of votes.
