### ISSUE TITLE
Suggestion: Adding MUBI rating

### ISSUE THREAD

**Issue by ghost** [duncanlang/Letterboxd-Extras#10]
Hello
Is it possible to add MUBI ratings, too?

Thanks

**Comment by duncanlang** [comment]
So what is MUBI, and where can I see the ratings? My searches come up with a streaming service so I'm not sure about ratings.

**Comment by hasan-atef01** [comment]
Yes, it's steaming service with curated films.
But it also can be used to rate films and make lists for free users, even
if the film isn't in their library.

Here is a list with their top-rated films,
https://mubi.com/lists/the-top-1000
Ratings are shown on the top right of the film page.

So, is it possible to add their ratings?
Thank you for your time.

**Comment by duncanlang** [comment]
Added MUBI in the latest (v3.8.0) release. It is disabled by default, check the extension settings to enable it.
The update is live on the Chrome and Firefox stores, Edge is still in review.
