### ISSUE TITLE
Suggestion: Adding FilmAffinity rating

### ISSUE THREAD

**Issue by rub9n** [duncanlang/Letterboxd-Extras#12]
Hi duncanlang,

First of all, thank you for this really nice script.

Could you please add FilmAffinity ratings too, just like you did with MUBI?

FilmAffinity is a movie recommendations website created in 2002 in Spain. The website is mostly used in Spain and Spanish-speaking countries, but it has some exclusive features, like the Movie Soulmates, which is not available elsewhere.
Anyway, here’s a link to the top-rated movies in FilmAffinity: https://www.filmaffinity.com/en/ranking.php?rn=ranking_fa_movies

PS: Could you please make the external links that you added (RT, META, MOJO, etc.) to open in a new tab rather than in the same tab? Just like the default IMDB and TMDB links.

All the best,
Ruben

**Comment by duncanlang** [comment]
I've added FilmAffinity in the latest release (v3.9.0), which is live on both Firefox and Chrome. FilmAffinity is disabled by default, so you have to go into the settings to enable it. Sadly, I was unable to scrape the rating counts per score to create a bar graph like Letterboxd or IMDb scores, so it just displays the rating out of 10.

I've also changed the links to open in a new tab/ I was actually unaware that the buttons worked differently as I would always middle click to open in a new tab.
