### ISSUE TITLE
Suggestion: Option to display Letterboxd star scores as score out of 10

### ISSUE THREAD

**Issue by MomoNaryan** [duncanlang/Letterboxd-Extras#13]
Thank you for this fantastic script! I'm really enjoying it so far.

When I'm rating films, I personally think in terms of a rating out of 10, which needs a quick mental conversion to Letterboxd's star ratings. I know that Letterboxd stores their ratings out of 10 and then converts them to stars for display. It would be lovely to have an option to display star ratings as out of 10 instead, with 1/2 star equal to 1 out of 10, 1 star equal to 2 out of 10, and so on.

I appreciate your time and consideration!

**Comment by duncanlang** [comment]
I've added this option in the latest release (v3.9.0), which is live on both Firefox and Chrome. It replaces the existing setting that converts the other ratings to 5-point scale with a new dropdown to select 10-point scale as an option.

**Comment by MomoNaryan** [comment]
This is fantastic, thank you for your hard work (and for listening to my silly little suggestion)!
