### ISSUE TITLE
10-point scale not working right!

### ISSUE THREAD

**Issue by NeoDerEchte** [duncanlang/Letterboxd-Extras#16]
I love your add on but there is one problem. 

For example, if a film has a 3.54/5, then it would be a 7.08/10. BUT it says 7.0 instead of 7.1 because the system doubled the 3.5 and not the 3.54

I hope you understand what i mean :)

Maybe you can fix this ;)

**Comment by duncanlang** [comment]
Fixed with v3.11.0 available now for Chrome and Firefox
