### ISSUE TITLE
Extra Option for Rotten Tomatoes? :)

### ISSUE THREAD

**Issue by NeoDerEchte** [duncanlang/Letterboxd-Extras#17]
Maybe you can make an option that rotten tomatoes only shows you the critics and not the audience?

Thank you :) Happy new year!

**Comment by duncanlang** [comment]
I could add the option, but I'm not sure if I understand the benefit?

**Comment by NeoDerEchte** [comment]
It's your decision. But I would like it :)

**Comment by duncanlang** [comment]
Added two checkboxes for Rotten Tomatoes to display the critic and audience scores (enabled by default). To only display critic as you want, you can now disable the checkbox for displaying the audience score.
![image](https://github.com/duncanlang/Letterboxd-Extras/assets/24242293/cb422bf1-a8ba-4426-ac02-5e4dcbfff97d)
(Also added for Metacritic for consistency)

Part of v3.11.0 available now for Chrome and Firefox.
