### ISSUE TITLE
Suggestion: Option to display IMDb Rating as x/5

### ISSUE THREAD

**Issue by Noahs-Git** [duncanlang/Letterboxd-Extras#2]
First of all thanks for making this add-on, it's really useful. I have an idea for improvement, maybe you could display the rounded imdb-rating divided by 2, so that it is more easily comparable with letterboxd ratings. But it could also be an option in the settings, because I don't know if everyone would like it this way.
For example [https://letterboxd.com/film/harakiri/](url) would display a 4.3 in the imdb section instead of the usual rating of 8.6, if enabled in the options.
Moreover, it would probably be required to also update the individual star-ratings.
I will look into the code and if this feature is wanted, I can try to add this and make a pull request.

**Comment by Noahs-Git** [comment]
Implemented and tested on Win10 Firefox 104.0.2 (64-Bit)
https://github.com/duncanlang/Letterboxd-Extras/pull/3#issue-1376182390

**Comment by Noahs-Git** [comment]
Just realized I should probably also add it for AniList and MyAnimeList. Will do that soon..

**Comment by Noahs-Git** [comment]
Implemented for Firefox: https://github.com/duncanlang/Letterboxd-Extras/pull/4#issue-1376408599

**Comment by duncanlang** [comment]
Merged
Released with v3.5.5
Thank you for the contribution.
