### ISSUE TITLE
Feature Request: Add TSPDT ranking

### ISSUE THREAD

**Issue by andbladi** [duncanlang/Letterboxd-Extras#20]
TSPDT is widely considered the definitive aggregate critic's list. It would be incredibly helpful to quickly see each individual film's ranking on this list within Letterboxd. For many of us, it says more than Rotten Tomatoes, Letterboxd or IMDb rankings.

Ideally, you could add the rankings on each film's page for both the [TSPDT 1,000 Greatest Films](https://www.theyshootpictures.com/gf1000_startinglist_table.php) (Starting List: 23,096 films) and the [TSPDT 21st Century's Most Acclaimed Films](https://www.theyshootpictures.com/21stcentury_startinglist_table.php) (Starting List: 11,344 films), if applicable.

No idea if this possible to implement, but it'd make one of my most used extensions even better!

**Comment by duncanlang** [comment]
I've added the TSPDT top 1000 as an option to be displayed in the latest version v.3.13.0. It is placed on the page below the film poster like where the Letterboxd top 250 indicator is.

Not directly related to this issue, but I've taken this as a chance to also add the rankings from the BFI as a separate option in addition.

**Comment by andbladi** [comment]
Incredible!On May 28, 2024, at 03:08, Duncan Lang ***@***.***> wrote:﻿
Closed #20 as completed.
