### ISSUE TITLE
Label 'Adult' is not displayed on film pages

### ISSUE THREAD

**Issue by reolcor** [duncanlang/Letterboxd-Extras#21]
**URL**: https://letterboxd.com/film/adam-yves/ (or any other from https://letterboxd.com/jlalibs/list/official-letterboxd-adult-film-megalist/)
**Browser / Version**: Firefox 126.0a1

**Problem type**: Cosmetic
**Description**: Label 'Adult' is not displayed with the extension enabled
**Steps to Reproduce**:
Open films from https://letterboxd.com/jlalibs/list/official-letterboxd-adult-film-megalist/ with the extension enabled 

![without_extension](https://github.com/duncanlang/Letterboxd-Extras/assets/6018312/64c43042-97e4-499b-84f3-3e2802aa1790)
![extension_enabled](https://github.com/duncanlang/Letterboxd-Extras/assets/6018312/4b4c0a03-d042-4e23-bc53-1ac71d9dd974)

**Comment by duncanlang** [comment]
Fixed in v3.12.0
