### ISSUE TITLE
Missing Rotten Tomatoes Audience Score

### ISSUE THREAD

**Issue by JmaJeremy** [duncanlang/Letterboxd-Extras#22]
For the Rotten Tomatoes score I'm only seeing the critics score; audience score is missing
![image](https://github.com/duncanlang/Letterboxd-Extras/assets/2232707/c70f2432-90ce-420e-aa5c-ef5a78aa746d)

**Comment by duncanlang** [comment]
Ahh, Rotten Tomatoes had yet another site change which broke the extension
Fixed in v3.12.1
