### ISSUE TITLE
Show the exact average rating and rating count

### ISSUE THREAD

**Issue by misaeldavid7** [duncanlang/Letterboxd-Extras#24]
I wish there was an option to see the exact average rating and rating count without having to hover over something.

For instance: when it comes to Letterboxd ratings, I'd like to see "4.32 based on 742,561 votes" instead of 4.3 and a rating distribution. 

I'd also like to see the average rating and rating count of Rotten Tomatoes, Metacritic, Mubi, FilmAffinity and all the other sites available.

**Comment by duncanlang** [comment]
I've added an option ('Display tooltips on page") in the latest update (3.14.0) which will display all of the rating tooltips as text below the ratings, which should work for what you want. The update is available today for Firefox and Chrome
