### ISSUE TITLE
Currently Missing Rotten Tomatoes and Metacritic Ratings

### ISSUE THREAD

**Issue by ThorDay** [duncanlang/Letterboxd-Extras#26]
I just noticed today that the ratings for Rotten Tomatoes and Metacritic are absent in Edge and Chrome.

IMDb is still there so the extension is partially working.

**Comment by ThorDay** [comment]
Ratings are working for some movies but not all, including Stop Making Sense, Bohemian Rhapsody, and Unfrosted. Sorry for the inconvenience.

**Comment by duncanlang** [comment]
Fixed in v3.12.2
Letterboxd made some changes to the HTML of the page which caused some errors.
