### ISSUE TITLE
Add SIMKL Ratings

### ISSUE THREAD

**Issue by Azmarine13** [duncanlang/Letterboxd-Extras#28]
Adding the ratings from SIMKL.com tracking site (For Movies, TV Shows, Anime)

Also has a dedicated documentation for RATING API: https://simkl.docs.apiary.io/#reference/ratings/ratings-api

**Comment by duncanlang** [comment]
I've added Simkl ratings in the latest update (3.14.0), which is available now for Firefox and Chrome.
It it disabled by default, so you will need to enable it in the extension options
