### ISSUE TITLE
Feature Request: add Letterboxd score on Google Knowledge Graph

### ISSUE THREAD

**Issue by prodan1234** [duncanlang/Letterboxd-Extras#31]
When searching for a movie on Google, their Knowledge Graph sometimes shows the Letterboxd score and sometimes doesn't. I'd like the extension to force show the score always. 
![CleanShot 2024-07-14 at 15 19 01@2x](https://github.com/user-attachments/assets/f57ce94d-bf66-43c4-a0a7-edc1e1bae966)
vs
![CleanShot 2024-07-14 at 15 19 21@2x](https://github.com/user-attachments/assets/45bdc52c-64d3-4869-adf9-bb6f49ce93a1)

**Comment by duncanlang** [comment]
Added in latest release, v3.15.1 currently available in Chrome and Firefox
It's been added as a new option because I didn't want the google.com permission that this feature requires to be mandatory for all users.
