### ISSUE TITLE
Feature request: Option to switch 5 stars to 10 stars system

### ISSUE THREAD

**Issue by sc113** [duncanlang/Letterboxd-Extras#32]
It would be quite useful to see and compare ratings in equivalent systems. So it would be handy to have an option to convert IMDB ratings to 5 stars or vice versa to convert Letterboxd ratings to 10-star system.

**Comment by duncanlang** [comment]
There is already an option, called "Convert Ratings", in the extension options that will adjust the ratings to either a 5-point or 10-point scale.

**Comment by sc113** [comment]
Oh, there's a scrolling bar on the right in the options. It was barely noticeable in the current layout on firefox, I apologise :)
