### ISSUE TITLE
Extension not working suddenly

### ISSUE THREAD

**Issue by Tetrax-10** [duncanlang/Letterboxd-Extras#43]
![image](https://github.com/user-attachments/assets/fb894efc-fcb7-4c0f-baa3-b6fa9e60e0ec)

<br>

![image](https://github.com/user-attachments/assets/f21f2921-307f-435e-8e3a-fa654b7b30e7)

It was working fine yesterday but suddenly it doesn't work today.

**Comment by duncanlang** [comment]
Fixed in latest version (v3.15.2) just posted for review.
Firefox has been approved and the update is available.
Chrome and Edge are still pending the review.

**Comment by duncanlang** [comment]
The update has passed the Chrome review and is now available for download. Edge is still pending.
