### ISSUE TITLE
Not Working in Edge

### ISSUE THREAD

**Issue by ThorDay** [duncanlang/Letterboxd-Extras#44]
It looks like it may not be working in Edge or Chrome.

**Comment by duncanlang** [comment]
Fixed in latest version (v3.15.2) just posted for review.
Chrome and Edge are still pending the review. Edge review is slower than Chrome or Firefox and usually takes up to a week to be available.

**Comment by duncanlang** [comment]
The update has passed the Chrome review and is now available for download. Edge is still pending.
