### ISSUE TITLE
Add Senscritique

### ISSUE THREAD

**Issue by artur309** [duncanlang/Letterboxd-Extras#5]
add a senscritique ranking, this idea was provided to me and I'm interesting to try add it.

> https://www.senscritique.com/film/venus_wars/389530
film example

**Comment by artur309** [comment]
> idea to implement if you like:
 - options to choose which platforms should be displayed

**Comment by duncanlang** [comment]
I've found that apollo.senscritique.com is a public facing GraphQL API. I have made some initial testing with it (no commits yet), and I will continue working on this.

I will also add options to disable the different ratings, should be pretty simple.

**Comment by artur309** [comment]
nice to hear that, glad help in some sort,
 i really wanted try do something but haven't had good time for such.

**Comment by duncanlang** [comment]
Added SensCritique in v3.6.0, now available on Firefox and Chrome.
By default, I have SenCritique disabled, it can be enabled in the options.

**Comment by artur309** [comment]
yooo nice thanks, great job. the person who wanted this will be grateful thanks !
