### ISSUE TITLE
Metacritic & IMDB not present

### ISSUE THREAD

**Issue by blakegearin** [duncanlang/Letterboxd-Extras#6]
Hello, I recently noticed that Metacritic and IMDB were not loading like they normally do. 

I turned on the debug option and looked at the console logs. Looks like there's an error occurring in the middle of operations. It seems likely that Letterboxd deployed an update that breaks the extensions reliance/assumption on the presence `.report-link`

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/17950836/198722946-658143c4-73b2-479b-878e-707b11757308.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/17950836/198724269-31cee5a6-284d-4a53-886c-26c389a7df9e.png">

**Versions:**
- Letterboxd Extras `3.5.5`
- macOS `11.5.2` (Big Sur)
- Firefox `106.0.2`, Build: `20221025065831`

**Preferences:**

<img width="655" alt="image" src="https://user-images.githubusercontent.com/17950836/198725029-442952e5-a1b9-4ebc-a82a-1729b81466f3.png">

**Comment by blakegearin** [comment]
**Note:** Also tried disabling uBlock Origin & Privacy Badger, replicating in a private browser window, and replicating on a separate machine; got the same behavior & error

**Comment by duncanlang** [comment]
Letterboxd changed the report button on film pages, fixed in v3.5.6.
