### ISSUE TITLE
Letterboxd-Style rating does not work with IMDb ratings

### ISSUE THREAD

**Issue by theczlowiek** [duncanlang/Letterboxd-Extras#7]
Hello, I'm using your extension on Opera GX and while the option "Convert ratings to Letterboxd-Style rating" works with MAL, it doesn't work with IMDb, by selecting this option and the option to display ratings from IMDb, the site doesn't work properly (it just doesn't display ratings from IMDb)

**Comment by duncanlang** [comment]
Fixed in v3.6.5.
Update published to Chrome and Firefox
