### ISSUE TITLE
Suggestion: make "display MPAA rating" a toggle in Preferences / Issue: CinemaScore not displaying

### ISSUE THREAD

**Issue by ryanjlee7** [duncanlang/Letterboxd-Extras#9]
For aesthetics' sake and personal preference, could MPAA rating become a toggle, able to be turned on and off?

Also: I'm on Firefox on a Mac, and CinemaScore isn't showing up for me when I toggle it on, regardless of the film. 
Thank you in advance; this extension is great for all the extra information it provides at a glance.

**Comment by duncanlang** [comment]
I will add an option for the MPAA rating for the next release (soon, hopefully)

CinemaScore's API has not been working for a while. I've tried contacting them, but of course I am a nobody so I didn't hear back. I will try again, but for now it's out of my hands.

**Comment by duncanlang** [comment]
Toggle for MPAA/MPA added in latest version v.3.7.0
